import type { Metadata } from "next";
import { Roboto, Bree_Serif, Poppins } from "next/font/google";
import "./globals.css";


const poppins = Poppins({
  subsets: ['latin'],
  weight: ["100", '300', '400', '500', '700', '900']
})

const breeSerif = Bree_Serif({
  subsets: ['latin'],
  // weight: ['400', '500', '700', '900']
  weight: "400"
})

const roboto = Roboto({
  subsets: ['latin'],
  weight: ["100", '300', '400', '500', '700', '900']
})

const bree = Bree_Serif({
  subsets: ['latin'],
  weight: ["400"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} ${breeSerif.className} ${bree.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
